# Generated by Django 3.1.6 on 2022-09-22 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(max_length=255, verbose_name="Наименование банка"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term_min",
                    models.PositiveSmallIntegerField(verbose_name="Срок ипотеки, ОТ"),
                ),
                (
                    "term_max",
                    models.PositiveSmallIntegerField(verbose_name="Срок ипотеки, ДО"),
                ),
                ("rate_min", models.FloatField(verbose_name="Ставка, ОТ")),
                ("rate_max", models.FloatField(verbose_name="Ставка, ДО")),
                (
                    "payment_min",
                    models.PositiveIntegerField(verbose_name="Сумма кредита, ОТ"),
                ),
                (
                    "payment_max",
                    models.PositiveIntegerField(verbose_name="Сумма кредита, ДО"),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer",
                        to="offers.bank",
                        verbose_name="Банк",
                    ),
                ),
            ],
        ),
    ]
